name: Build Project

on:
  push

jobs:
  remove-caches:
    name: Remove all GA caches
    runs-on: ubuntu-latest
    steps:
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      - uses: easimon/wipe-cache@main
      